### ISSUE TITLE
Add Cache-Control headers to redirect responses

### ISSUE THREAD

**Issue by ineale2** [awslabs/cognito-at-edge#18]
#### What would you like to be added:
* Set cache-control and pragma headers to the redirect responses

#### Why is this needed:
* When the Authenticator redirects to Cognito or with the set-cookies header, some browsers (IE11 in specific) cache the 302 response as no cache-control headers are set. 
* When subsequent requests come (with valid cookies), IE11 will retrieve the cached 302 response and get stuck in a redirect loop

**Comment by jeandek** [comment]
Merged and will be included in next release.
