### ISSUE TITLE
Switch to typescript

### ISSUE THREAD

**Issue by eddie-atkinson** [awslabs/cognito-at-edge#20]
#### What would you like to be added:
I am filing this issue to gauge the interest of the maintainers of this project in switching to Typescript. I have found this project useful in my own work and think it would be a big QoL improvement if it were type annotated. 

I also wanted to gauge how responsive the maintainers of this project would be to PRs to add functionality. For my use case I'd love to add a callback to the `handle` function which allows me to change the return logic on the basis of a user's decoded token. For example, to return a 403 error if a user doesn't have a Cognito group granting them access. 

#### Why is this needed:
* Given how long it takes to redeploy Lambda@Edge functions, catching silly errors at compile time would improve DX a lot

**Comment by jeandek** [comment]
Hi @eddie-atkinson,

Switching to Typescript is definitely something we'd like to do, though I can't commit to a specific roadmap.

We're open to PRs for both bug fixes and new functionality. For the latter, we recommend that you reach out to us to make sure this is something we'd be interested in adding. Your proposal would be a worthwhile addition to the package, we'd definitely be interested.

Cheers,
Jean

**Comment by pedromgarcia** [comment]
Hi @piotrekwitkowski,

Thanks for the PR, changes has been merged and will be included in the next release.
