### ISSUE TITLE
Double Decoding of the QueryParams

### ISSUE THREAD

**Issue by AbhiPartha** [awslabs/cognito-at-edge#23]
#### What happened:
The code double decodes the query params resulting in malformed queryParam or altered queryParam.

#### What did you expect to have happen: 
The queryParam to be return as such it was called.

#### How to reproduce this (as precisely and succinctly as possible): 
Simply use the library and call with encoded queryParam and see the double decoding happening.

#### Anything else you think we should know? 
The fix is in https://github.com/awslabs/cognito-at-edge/blob/main/index.js#L180
Removing the extra decoding might solve the issue.

#### Environment: 
- version of cognito-at-edge being used: 1.1.0
- node version of code base which uses cognito-at-edge: 14x

**Comment by jeandek** [comment]
Hi @AbhiPartha ,

Thanks for opening this issue and submitting a PR. I'm currently testing it and I'm observing some unexpected encoding differences between my test setup and another environment which uses the package. I'll keep you updated.

**Comment by jeandek** [comment]
Merged and will be included in the next release.
