### ISSUE TITLE
Support SameSite directive

### ISSUE THREAD

**Issue by ckifer** [awslabs/cognito-at-edge#47]
#### What would you like to be added:
As a user with secure websites I would like control over all common cookie directives. Recently HttpOnly was added to the library - this would be to support [SameSite](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) as well.

#### Why is this needed:
* Provide flexible configuration to `cognito-at-edge`
* improve security config options

**Comment by ckifer** [comment]
Should probably wait on #46 to merge

**Comment by ckifer** [comment]
Resolved in #50

**Comment by fknittel** [comment]
@ckifer Thanks for the enhancement! Do you know whether this will be released anytime soon? We're keen on using it in our project.

**Comment by ckifer** [comment]
I also need to use it on next release - @jeandek or @borisfba ?

**Comment by jeandek** [comment]
@ckifer @fknittel : Sorry about the delay. I will try to publish the new version by the end of the week (probably Thursday).

**Comment by ckifer** [comment]
Thanks!

**Comment by jeandek** [comment]
@ckifer @fknittel We published version 1.3.2 of the package this morning. Here are the [change notes](https://github.com/awslabs/cognito-at-edge/releases/tag/1.3.2).

**Comment by ckifer** [comment]
Thank you!!
