### ISSUE TITLE
cognito-at-edge is not able to redirect to IdP

### ISSUE THREAD

**Issue by nagendrakumar02** [awslabs/cognito-at-edge#56]
I am using federated cognito, where the user is redirected to SAML IdP. Cognito-at-edge does not expose the "scope" and "idp_identifier". this is based on the documentation from the aws site https://docs.aws.amazon.com/cognito/latest/developerguide/authorization-endpoint.html

#### How to reproduce this (as precisely and succinctly as possible): Create a new Cognito Pool and use a third party  identity provider (like SAML). Set the properties from the pool

const authenticator = new Authenticator({
  // Replace these parameter values with those of your own environment
  region: 'us-west-2', // user pool region
  userPoolId: 'ddffff', // user pool ID
  userPoolAppId: 'xxxxx', // user pool app client ID
  userPoolDomain: '.auth.us-west-2.amazoncognito.com', // user pool domain
});

#### Environment: 
- version of cognito-at-edge being used: Latest version
- node version of code base which uses cognito-at-edge:16.x
- other:

-

**Comment by jeandek** [comment]
Hi @nagendrakumar02 ,

I understand that when using cognito-at-edge's `Authenticator.handle` method to handle your CloudFront's distribution viewer request your website's visitors are not being redirected to your SAML identity provider. Would you mind describing the behavior that you're seeing instead?

**Comment by nagendrakumar02** [comment]
Hi @jeandek,

I was able to get it working by forking the code and added 2 optional parameters (idprovider and scope). If the 2 parameters are set, it is appended to the redirect. This has fixed my issue.

**Comment by nagendrakumar02** [comment]
Hi @jeandek,

I was able to get it working by forking the code and added 2 optional parameters (idprovider and scope). If the 2 parameters are set, it is appended to the redirect url. This has fixed my issue.

**Comment by theo-rogers** [comment]
> 

Are you able to make a PR for these changes? I need this functionality as well.

**Comment by nagendrakumar02** [comment]
I forked the code from the main branch to support redirecting to IdP.

https://github.com/nagendrakumar02/cognito-at-edge

- -

Nagendra Dattatreya

CTO

 973.960.3951

 zappyride.com <https://www.zappyride.com/>

<https://www.zappyride.com/>

[image: LinkedIn] <https://www.linkedin.com/company/27054560>[image:
Twitter] <https://twitter.com/zappyride>

**Comment by nagendrakumar02** [comment]
2 new parameters are added

_idpIdentifier: Name of the IdP
_scope: scope

To read more about this follow this article

https://docs.aws.amazon.com/cognito/latest/developerguide/authorization-endpoint.html



- -

Nagendra Dattatreya

CTO

 973.960.3951

 zappyride.com <https://www.zappyride.com/>

<https://www.zappyride.com/>

[image: LinkedIn] <https://www.linkedin.com/company/27054560>[image:
Twitter] <https://twitter.com/zappyride>

**Comment by Jordan-Eckowitz** [comment]
@nagendrakumar02 was this ever merged into this package? I need this feature too.

**Comment by mrtimp** [comment]
Looks like the PR was closed and not merged: https://github.com/awslabs/cognito-at-edge/pull/73
